# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-17 18:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodtaskerapp', '0002_auto_20170217_1614'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='phome',
            new_name='phone',
        ),
    ]
